spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/p2p?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

logging:
  path: "../xxy-logs/dev"
  level:
    root: info
    org.springframework.web: debug

logback:
  logRoot: ../p2p-logs/dev
  logLevel: info
