spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
      favicon:
        enable: false;
server:
  port: 8088
  tomcat:
    max-threads: 400
    uri-encoding: UTF-8

mybatis:
  configuration:
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    lazyLoadTriggerMethods: ""
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:com/xxy/p2p/dao/mapping/*-sql-mapping.xml


